name: CI

on:
  push:
    branches: [main, integration/**]
  pull_request:
    branches: [main, integration/**]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [20, 24]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Format check
        run: npm run format:check
      - name: OpenAPI lint
        run: npm run openapi:lint
      - name: Tests
        run: npm test -- --ci --reporters=default
      - name: Coverage
        run: npm run test:coverage
